// change div background colors with help of these classes

const bgColors = [
  "bg-primary",
  "bg-primary-subtle",
  "bg-secondary",
  "bg-secondary-subtle",
  "bg-success",
  "bg-success-subtle",
  "bg-danger",
  "bg-danger-subtle",
  "bg-warning",
  "bg-warning-subtle",
  "bg-info",
  "bg-info-subtle",
  "bg-light",
  "bg-light-subtle",
  "bg-dark",
  "bg-dark-subtle",
  "bg-body-secondary",
  "bg-body-tertiary",
  "bg-body",
  "bg-black",
  "bg-white",
  "bg-transparent",
];
